IMPORT LIBRERIE E DATASET POLLUTANT TRANSFERS

In [1]:
#import dataset e librerie 

import numpy as np
import pandas as pd

df = pd.read_csv('Pollutant_Transfers_new.csv' ,sep =';')


df.head()

,FacilityID,NationalID,FacilityName,StreetName,BuildingNumber,PostalCode,City,CountryName,Lat,Long,CompetentAuthorityName,MainIAActivityCode,MainIASectorName,MainIAActivityName,MainIASubActivityName,MainActivityIndicator,ReportingYear,PollutantName,PollutantGroupName,Quantity
0,5752,1011210116,Mondi Business Paper Austria AG Standort: Papi...,Haidm�hlstra�e 2,NaN,3363.0,Amstetten,Austria,"48,05","14,8",Not transferred from EPER,EPER_6.1,Other Annex I activities,"Pulp, paper or board production",NaN,True,2001,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,625000
1,5757,1012110129,Ganahl Aktiengesellschaft (Papierfabrik),Rotfarbweg 5,NaN,6820.0,Frastanz,Austria,"47,216667","9,633333",Not transferred from EPER,EPER_6.1,Other Annex I activities,"Pulp, paper or board production",NaN,True,2001,Lead and compounds (as Pb),Heavy metals,"29,8"
2,5757,1012110129,Ganahl Aktiengesellschaft (Papierfabrik),Rotfarbweg 5,NaN,6820.0,Frastanz,Austria,"47,216667","9,633333",Not transferred from EPER,EPER_6.1,Other Annex I activities,"Pulp, paper or board production",NaN,True,2001,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,522000
3,5758,1012310124,Fresenius Kabi Austria GmbH Zweigniederlassung...,Estermannstra�e 17,NaN,4020.0,Linz,Austria,"48,3","14,283333",Not transferred from EPER,EPER_4.5,Chemical industry,Pharmaceutical products,NaN,True,2001,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,301000
4,5789,1016610659,Obersteirische Molkerei - Standort Knittelfeld,Anton-Regnerstra�e 11,NaN,8720.0,Knittelfeld,Austria,"47,216667","14,816667",Not transferred from EPER,EPER_6.4,Other Annex I activities,"Slaughterhouses, milk, animal and vegetable ra...",NaN,True,2001,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,97000

In [2]:
df.tail()

,FacilityID,NationalID,FacilityName,StreetName,BuildingNumber,PostalCode,City,CountryName,Lat,Long,CompetentAuthorityName,MainIAActivityCode,MainIASectorName,MainIAActivityName,MainIASubActivityName,MainActivityIndicator,ReportingYear,PollutantName,PollutantGroupName,Quantity
71579,15620,vl01856089000144,LANXESS,Scheldelaan,420,2040.0,Antwerpen,Belgium,"51,34265","4,2788363",Vlaamse Milieumaatschappij (VMM),4.(a),Chemical industry,Chemical installations for the production on a...,NaN,False,2016,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,1150000
71580,15620,vl01856089000144,LANXESS,Scheldelaan,420,2040.0,Antwerpen,Belgium,"51,34265","4,2788363",Vlaamse Milieumaatschappij (VMM),4.(a),Chemical industry,Chemical installations for the production on a...,NaN,True,2016,Total nitrogen,Inorganic substances,68500
71581,15620,vl01856089000144,LANXESS,Scheldelaan,420,2040.0,Antwerpen,Belgium,"51,34265","4,2788363",Vlaamse Milieumaatschappij (VMM),4.(a),Chemical industry,Chemical installations for the production on a...,NaN,False,2016,Total nitrogen,Inorganic substances,68500
71582,15620,vl01856089000144,LANXESS,Scheldelaan,420,2040.0,Antwerpen,Belgium,"51,34265","4,2788363",Vlaamse Milieumaatschappij (VMM),4.(a),Chemical industry,Chemical installations for the production on a...,NaN,False,2016,Total nitrogen,Inorganic substances,68500
71583,14723,vl01747956000148,VAN-O-BEL,Transvaalstraat,35,8793.0,Waregem,Belgium,"50,900112","3,4072957",Vlaamse Milieumaatschappij (VMM),8.(a),Animal and vegetable products from the food an...,Slaughterhouses,NaN,True,2016,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,68300

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71584 entries, 0 to 71583
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   FacilityID              71584 non-null  int64
 1   NationalID              71584 non-null  object
 2   FacilityName            71582 non-null  object
 3   StreetName              69898 non-null  object
 4   BuildingNumber          51347 non-null  object
 5   PostalCode              51141 non-null  float64
 6   City                    70354 non-null  object
 7   CountryName             71584 non-null  object
 8   Lat                     71584 non-null  object
 9   Long                    71584 non-null  object
 10  CompetentAuthorityName  71584 non-null  object
 11  MainIAActivityCode      71584 non-null  object
 12  MainIASectorName        71584 non-null  object
 13  MainIAActivityName      71584 non-null  object
 14  MainIASubActivityName   16395 non-null  object
 15  MainActivityIndicator   71584 non-null  bool
 16  ReportingYear           71584 non-null  int64
 17  PollutantName           71584 non-null  object
 18  PollutantGroupName      71584 non-null  object
 19  Quantity                71584 non-null  object
dtypes: bool(1), float64(1), int64(2), object(16)
memory usage: 10.4+ MB

In [5]:
#trasformo quantità di inquinante misurato in kg in float usando una funzione lambda

df['Quantity'].apply(lambda x: float(x.replace(',','.')))

0         625000.0
1             29.8
2         522000.0
3         301000.0
4          97000.0
           ...
71579    1150000.0
71580      68500.0
71581      68500.0
71582      68500.0
71583      68300.0
Name: Quantity, Length: 71584, dtype: float64