In [ ]:
IMPORT LIBRERIE E DATASET POLLUTANT RELEASE

In [2]:
#import dataset e librerie 

import numpy as np
import pandas as pd

df = pd.read_csv('Pollutant_Release_new.csv' ,sep =';')


df.head()

,FacilityID,NationalID,FacilityName,StreetName,BuildingNumber,PostalCode,City,CountryName,Lat,Long,...,MainIAActivityCode,MainIASectorName,MainIAActivityName,MainIASubActivityName,MainActivityIndicator,ReportingYear,PollutantName,PollutantGroupName,TotalQuantity,ReleaseMediumName
0,192129,1124.0040.02,Sele avfallsplass - Deponi,Kleppvegen 837,NaN,4354,Voll,Norway,"58,8203773","5,578351",...,5.(d),Waste and waste water management,Landfills (see note in Guidance Document),NaN,True,2015,Total nitrogen,Inorganic substances,53300,Water
1,192129,1124.0040.02,Sele avfallsplass - Deponi,Kleppvegen 837,NaN,4354,Voll,Norway,"58,8203773","5,578351",...,5.(d),Waste and waste water management,Landfills (see note in Guidance Document),NaN,True,2015,Di-(2-ethyl hexyl) phthalate (DEHP),Other organic substances,"3,09",Water
2,192129,1124.0040.02,Sele avfallsplass - Deponi,Kleppvegen 837,NaN,4354,Voll,Norway,"58,8203773","5,578351",...,5.(d),Waste and waste water management,Landfills (see note in Guidance Document),NaN,True,2015,"1,1,1-trichloroethane",Chlorinated organic substances,"0,0482",Water
3,4659,06K000239,"ArcelorMittal Poland S.A., Oddzia? w Krakowie",Ujastek 1,NaN,30-969,Krak�w,Poland,"50,080333","20,092361",...,2.(a),Productiona and processing of metals,Metal ore (including sulphide ore) roasting or...,NaN,False,2013,Hydro-fluorocarbons (HFCs),Greenhouse gases,190,Air
4,4659,06K000239,"ArcelorMittal Poland S.A., Oddzia? w Krakowie",Ujastek 1,NaN,30-969,Krak�w,Poland,"50,080333","20,092361",...,2.(a),Productiona and processing of metals,Metal ore (including sulphide ore) roasting or...,NaN,False,2013,Methane (CH4),Greenhouse gases,536000,Air

In [3]:
df.tail()

,FacilityID,NationalID,FacilityName,StreetName,BuildingNumber,PostalCode,City,CountryName,Lat,Long,...,MainIAActivityCode,MainIASectorName,MainIAActivityName,MainIASubActivityName,MainActivityIndicator,ReportingYear,PollutantName,PollutantGroupName,TotalQuantity,ReleaseMediumName
652346,45039,07-01-114014,Rasselstein GmbH,Koblenzer Str.,141,56626,Andernach,Germany,"50,43481013","7,426398842",...,2.(f),Productiona and processing of metals,Installations for surface treatment of metals ...,NaN,False,2009,Nickel and compounds (as Ni),Heavy metals,131,Water
652347,45039,07-01-114014,Rasselstein GmbH,Koblenzer Str.,141,56626,Andernach,Germany,"50,43481013","7,426398842",...,2.(f),Productiona and processing of metals,Installations for surface treatment of metals ...,NaN,False,2009,Total organic carbon (TOC) (as total C or COD/3),Other organic substances,80700,Water
652348,45039,07-01-114014,Rasselstein GmbH,Koblenzer Str.,141,56626,Andernach,Germany,"50,43481013","7,426398842",...,2.(f),Productiona and processing of metals,Installations for surface treatment of metals ...,NaN,False,2009,Zinc and compounds (as Zn),Heavy metals,184,Water
652349,45706,06-09-162-0025-0001,BMW Werk 1.1,Lerchenauer Str.,76,80788,M�nchen,Germany,"48,17917516","11,56150203",...,9.(c),Other activities,Installations for the surface treatment of sub...,NaN,True,2009,Non-methane volatile organic compounds (NMVOC),Other gases,374000,Air
652350,46133,06-09-775-2109-0001,EvoBus GmbH,Carl-Zeiss-Str.,2,89231,Neu-Ulm,Germany,"48,39309564","10,03985627",...,9.(c),Other activities,Installations for the surface treatment of sub...,NaN,True,2009,Non-methane volatile organic compounds (NMVOC),Other gases,288000,Air

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652351 entries, 0 to 652350
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   FacilityID              652351 non-null  int64
 1   NationalID              652351 non-null  object
 2   FacilityName            651263 non-null  object
 3   StreetName              645937 non-null  object
 4   BuildingNumber          418206 non-null  object
 5   PostalCode              650638 non-null  object
 6   City                    638945 non-null  object
 7   CountryName             652351 non-null  object
 8   Lat                     652351 non-null  object
 9   Long                    652351 non-null  object
 10  CompetentAuthorityName  652351 non-null  object
 11  MainIAActivityCode      652351 non-null  object
 12  MainIASectorName        652351 non-null  object
 13  MainIAActivityName      652351 non-null  object
 14  MainIASubActivityName   133018 non-null  object
 15  MainActivityIndicator   652351 non-null  bool
 16  ReportingYear           652351 non-null  int64
 17  PollutantName           652351 non-null  object
 18  PollutantGroupName      652351 non-null  object
 19  TotalQuantity           652351 non-null  object
 20  ReleaseMediumName       652351 non-null  object
dtypes: bool(1), int64(2), object(18)
memory usage: 100.2+ MB

In [21]:
df['ReleaseMediumName'].value_counts()

Air      392948
Water    256100
Soil       3303
Name: ReleaseMediumName, dtype: int64

In [23]:
df['PollutantGroupName'].value_counts()

Other gases                       214803
Heavy metals                      162093
Greenhouse gases                   90362
Inorganic substances               82623
Other organic substances           69843
Chlorinated organic substances     29707
Pesticides                          2920
Name: PollutantGroupName, dtype: int64

In [18]:
italia = df.loc[(df['CountryName'] == 'Italy') & (df['City'] == 'TORINO')]
italia

,FacilityID,NationalID,FacilityName,StreetName,BuildingNumber,PostalCode,City,CountryName,Lat,Long,...,MainIAActivityCode,MainIASectorName,MainIAActivityName,MainIASubActivityName,MainActivityIndicator,ReportingYear,PollutantName,PollutantGroupName,TotalQuantity,ReleaseMediumName
2358,69,01001010,AZIENDA ENERGETICA METROPOLITANA TORINO S.P.A....,"CORSO SALVEMINI,5 TORINO (TO)",NaN,10137,TORINO,Italy,"45,043611","7,629722",...,EPER_1.1,Energy industries,Combustion installations > 50 MW,NaN,True,2004,Nitrogen oxides (NOx/NO2),Other gases,164000,Air
2499,70,01001011,AZIENDA ENERGETICA METROPOLITANA TORINO S.P.A....,"VIA DELLE PRIMULE,13 TORINO (TO)",NaN,10151,TORINO,Italy,"45,100833","7,630278",...,EPER_1.1,Energy industries,Combustion installations > 50 MW,NaN,True,2001,Sulphur oxides (SOx/SO2),Other gases,288000,Air
2500,70,01001011,AZIENDA ENERGETICA METROPOLITANA TORINO S.P.A....,"VIA DELLE PRIMULE,13 TORINO (TO)",NaN,10151,TORINO,Italy,"45,100833","7,630278",...,EPER_1.1,Energy industries,Combustion installations > 50 MW,NaN,True,2001,Nickel and compounds (as Ni),Heavy metals,190,Air
2501,70,01001011,AZIENDA ENERGETICA METROPOLITANA TORINO S.P.A....,"VIA DELLE PRIMULE,13 TORINO (TO)",NaN,10151,TORINO,Italy,"45,100833","7,630278",...,EPER_1.1,Energy industries,Combustion installations > 50 MW,NaN,True,2001,Nitrogen oxides (NOx/NO2),Other gases,924000,Air
3224,70,01001011,AZIENDA ENERGETICA METROPOLITANA TORINO S.P.A....,"VIA DELLE PRIMULE,13 TORINO (TO)",NaN,10151,TORINO,Italy,"45,100833","7,630278",...,EPER_1.1,Energy industries,Combustion installations > 50 MW,NaN,True,2004,Sulphur oxides (SOx/SO2),Other gases,291000,Air
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563133,87,2007001835,Comprensorio industriale di Mirafiori (TO),CORSO SETTEMBRINI,90,10135,TORINO,Italy,"45,072222","7,678611",...,1.(c),Energy sector,Thermal power stations and other combustion in...,NaN,False,2017,Carbon dioxide (CO2),Greenhouse gases,110000000,Air
572611,191451,2008000003,Luigi Lavazza SpA - Stabilimento di Torino,Strada Settimo,410,10154,TORINO,Italy,"45,072222","7,678611",...,8.(b),Animal and vegetable products from the food an...,Treatment and processing intended for the prod...,NaN,True,2017,Nitrogen oxides (NOx/NO2),Other gases,159000,Air
576054,81,2007001836,Mirafiori Plant,Corso Enrico Tazzoli,75,10135,TORINO,Italy,"45,030277","7,631111",...,9.(c),Other activities,Installations for the surface treatment of sub...,NaN,True,2017,Non-methane volatile organic compounds (NMVOC),Other gases,369000,Air
576055,81,2007001836,Mirafiori Plant,Corso Enrico Tazzoli,75,10135,TORINO,Italy,"45,030277","7,631111",...,9.(c),Other activities,Installations for the surface treatment of sub...,NaN,True,2017,Nitrogen oxides (NOx/NO2),Other gases,130000,Air
576056,81,2007001836,Mirafiori Plant,Corso Enrico Tazzoli,75,10135,TORINO,Italy,"45,030277","7,631111",...,9.(c),Other activities,Installations for the surface treatment of sub...,NaN,True,2017,Naphthalene,Other organic substances,271,Air

In [31]:
#trasformo quantità di inquinante misurato in kg in float usando una funzione lambda

df['TotalQuantity'].apply(lambda x: float(x.replace(',','.')))

0          53300.0000
1              3.0900
2              0.0482
3            190.0000
4         536000.0000
             ...
652346       131.0000
652347     80700.0000
652348       184.0000
652349    374000.0000
652350    288000.0000
Name: TotalQuantity, Length: 652351, dtype: float64